# Generated by Django 3.0.7 on 2020-07-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('img_about', models.ImageField(upload_to='home/about')),
                ('about_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients_div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_clients', models.ImageField(upload_to='home/clients')),
            ],
        ),
        migrations.CreateModel(
            name='Home_top_div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptison', models.TextField()),
                ('img_top_div', models.ImageField(upload_to='home/services')),
            ],
        ),
        migrations.CreateModel(
            name='Services_div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
    ]
