# Generated by Django 3.0.7 on 2020-09-06 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_oder_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oder_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_id', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('oder_tb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.oder_tb')),
            ],
        ),
    ]
