# Generated by Django 3.0.7 on 2020-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('vacancy', models.IntegerField(default=None, null=True)),
                ('job_responsibility', models.TextField()),
                ('employment_status', models.CharField(choices=[('FUll Time', 'FUll Time'), ('Part Time', 'Part Time'), ('Contractual', 'Contractual')], default='FUll Time', max_length=50)),
                ('work_place', models.CharField(choices=[('Work from Home', 'Work from Home'), ('Work at Office', 'Work at Office')], default='Work from Home', max_length=50)),
                ('education', models.TextField()),
                ('experience', models.CharField(max_length=500)),
                ('additional_requirment', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
